version: '3.2'
services:
  user-app:
   image: user-app
   build: authservice/
   restart: always
   network_mode: host
   ports:
     - 8001:8001
   expose:
     - 8001
   depends_on:
     - movie-mysql
  movie-app:
   image: movie-app
   build: moviecruiserserverapplication/
   restart: always
   network_mode: host
   ports:
     - 8000:8000
   expose:
     - 8000
   depends_on:
     - movie-mysql

  movie-mysql:
   image: mysql:5.5
   network_mode: host
   ports:
     - "3306:3306"
   environment:
     MYSQL_ROOT_PASSWORD: root
     MYSQL_DATABASE: moviedb
     MYSQL_USER: app_root
     MYSQL_PASSWORD: root123
   volumes:
     - /opt/movie/mysqldb:/var/lib/mysql
  angular:
    image: angular-app
    build: Frontend
    network_mode: host
    container_name: angular-docker
    ports:
      - 4200:4200
